#  <span style="color:orange">Binary Classification Tutorial (CLF102) - Level Intermediate</span>

**Created using: PyCaret 2.2** <br />
**Date Updated: November 20, 2020**

# 1.0 Tutorial Objective
Welcome to the Binary Classification Tutorial **(CLF102)** - Level Intermediate. This tutorial assumes that you have completed __[Binary Classification Tutorial (CLF101) - Level Beginner](https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Beginner%20-%20%20CLF101.ipynb)__. If you haven't used PyCaret before and this is your first tutorial, we strongly recommend you to go back and progress through the beginner tutorial to understand the basics of working in PyCaret.

In this tutorial we will use the `pycaret.classification` module to learn:

* **Normalization:**  How to normalize and scale the dataset
* **Transformation:**  How to apply transformations that make the data linear and approximately normal
* **Ignore Low Variance:**  How to remove features with statistically insignificant variances to make the experiment more efficient
* **Remove Multi-collinearity:**  How to remove multi-collinearity from the dataset to boost performance of Linear algorithms
* **Group Features:**  How to extract statistical information from related features in the dataset
* **Bin Numeric Variables:**  How to bin numeric variables and transform numeric features into categorical ones using 'sturges' rule
* **Model Ensembling and Stacking:**  How to boost model performance using several ensembling techniques such as Bagging, Boosting, Soft/hard Voting and Generalized Stacking
* **Model Calibration:**  How to calibrate probabilities of a classification model
* **Experiment Logging:**  How to log experiments in PyCaret using MLFlow backend

Read Time : Approx 60 Minutes


## 1.1 Installing PyCaret
If you haven't installed PyCaret yet, please follow the link to __[Beginner's Tutorial](https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Beginner%20-%20%20CLF101.ipynb)__ for instructions on how to install.

## 1.2 Pre-Requisites
- Python 3.6 or greater
- PyCaret 2.0 or greater
- Internet connection to load data from pycaret's repository
- Completion of Binary Classification Tutorial (CLF101) - Level Beginner

## 1.3 For Google colab users:
If you are running this notebook on Google colab, run the following code at top of your notebook to display interactive visuals.<br/>
<br/>
`from pycaret.utils import enable_colab` <br/>
`enable_colab()`

## 1.4 See also:
- __[Binary Classification Tutorial (CLF101) - Level Beginner](https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Beginner%20-%20%20CLF101.ipynb)__
- __[Binary Classification Tutorial (CLF103) - Level Expert](https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Expert%20-%20CLF103.ipynb)__

# 2.0 Brief overview of techniques covered in this tutorial
Before we get into the practical execution of the techniques mentioned above in the Section 1, it is important to understand what these techniques are and when to use them. More often than not most of these techniques will help linear and parametric algorithms, however it is not suprising to also see performance gains in tree-based models. The below explanations are only brief and we recommend that you to do extra reading to dive deeper and get a more thorough understanding of these techniques.

- **Normalization:** Normalization / Scaling (often used interchangeably with standardization) is used to transform the actual values of numeric variables in a way that provides helpful properties for machine learning. Many algorithms such as Logistic Regression, Support Vector Machine, K Nearest Neighbors and Naive Bayes assume that all features are centered around zero and have variances that are at at the same level of order. If a particular feature in a dataset has a variance that is larger in order of magnitude than other features, the model may not understand all features correctly and could perform poorly. For instance, in the dataset we are using for this example the `AGE` feature ranges between 21 to 79 while other numeric features range from 10,000 to 1,000,000. __[Read more](https://sebastianraschka.com/Articles/2014_about_feature_scaling.html#z-score-standardization-or-min-max-scaling)__ <br/>
<br/>
- **Transformation:** While normalization transforms the range of data to remove the impact of magnitude in variance, transformation is a more radical technique as it changes the shape of the distribution so that transformed data can be represented by a normal or approximate normal distirbution. In general, you should transform the data if using algorithms that assume normality or a gaussian distribution. Examples of such models are Logistic Regression, Linear Discriminant Analysis (LDA) and Gaussian Naive Bayes. (Pro tip: any method with “Gaussian” in the name probably assumes normality.) __[Read more](https://en.wikipedia.org/wiki/Power_transform)__<br/>
<br/>
- **Ignore Low Variance:** Datasets can sometimes contain categorical features that have a single unique or small number of values across samples. This kind of features are not only non-informative and add no value but are also sometimes harmful for few algorithms. Imagine a feature with only one unique value or few dominant unique values accross samples, they can be removed from the dataset by using the ignore low variance feature in PyCaret. <br/>
<br/>
- **Multi-collinearity:** Multi-collinearity is a state of very high intercorrelations or inter-associations among the independent features in the dataset. It is a type of disturbance in the data that is not handled well by machine learning models (mostly linear algorithms). Multi-collinearity may reduce overall coefficient of the model and cause unpredictable variance. This will lead to overfitting where the model may do great on a known training set but will fail with an unknown testing set. __[Read more](https://towardsdatascience.com/multicollinearity-in-data-science-c5f6c0fe6edf)__<br/>
<br/>
- **Group Features:** Sometimes datasets may contain features that are related at a sample level. For example in the `credit` dataset there are features called `BILL_AMT1 .. BILL_AMT6` which are related in such a way that `BILL_AMT1` is the amount of the bill 1 month ago and `BILL_AMT6` is the amount of the bill 6 months ago. Such features can be used to extract additional features based on the statistical properties of the distribution such as mean, median, variance, standard deviation etc. <br/>
<br/>
- **Bin Numeric Variables:** Binning or discretization is the process of transforming numerical variables into categorical features. An example would be the Age variable which is a continious distribution of numeric values that can be discretized into intervals (10-20 years, 21-30 etc.). Binning may improve the accuracy of a predictive model by reducing the noise or non-linearity in the data. PyCaret automatically determines the number and size of bins using Sturges rule.  __[Read more](https://www.vosesoftware.com/riskwiki/Sturgesrule.php)__<br/>
<br/>
- **Model Ensembling and Stacking:** Ensemble modeling is a process where multiple diverse models are created to predict an outcome. This is achieved either by using many different modeling algorithms or using different samples of training data sets. The ensemble model then aggregates the predictions of each base model resulting in one final prediction for the unseen data. The motivation for using ensemble models is to reduce the generalization error of the prediction. As long as the base models are diverse and independent, the prediction error of the model decreases when the ensemble approach is used. The two most common methods in ensemble learning are `Bagging` and `Boosting`. Stacking is also a type of ensemble learning where predictions from multiple models are used as input features for a meta model that predicts the final outcome. __[Read more](https://blog.statsbot.co/ensemble-learning-d1dcd548e936)__<br/>
<br/>

# 3.0 Dataset for the Tutorial

For this tutorial we will be using the same dataset that was used in __[Binary Classification Tutorial (CLF101) - Level Beginner](https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Beginner%20-%20%20CLF101.ipynb)__

#### Dataset Acknowledgements:
Lichman, M. (2013). UCI Machine Learning Repository. Irvine, CA: University of California, School of Information and Computer Science.

The original dataset and data dictionary can be __[found here](https://archive.ics.uci.edu/ml/datasets/default+of+credit+card+clients)__ at the UCI Machine Learning Repository.

# 4.0 Getting the Data

You can download the data from the original source __[found here](https://archive.ics.uci.edu/ml/datasets/default+of+credit+card+clients)__ and load it using the pandas read_csv function or you can use PyCaret's data respository to load the data using the get_data function (This will require an internet connection).

In [1]:
# from pycaret.datasets import get_data
# dataset = get_data('credit', profile=True)
import pandas as pd

dataset = pd.read_excel('C:/Users/Stavros/Desktop/0. Dummy/0_Dummy.xlsx')

Notice that when the `profile` parameter is to `True`, it displays a data profile for exploratory data analysis. Several pre-processing steps as discussed in section 2 above will be performed in this experiment based on this analysis. Let's summarize how the profile has helped make critical pre-processing choices with the data.

- **Missing Values:** There are no missing values in the data. However, we still need imputers in our pipeline just in case the new unseen data has missing values (not applicable in this case). When you execute the `setup()` function, imputers are created and stored in the pipeline automatically. By default, it uses a mean imputer for numeric values and a constant imputer for categorical. This can be changed using the `numeric_imputation` and `categorical_imputation` parameters in `setup()`. <br/>
<br/>
- **Multicollinearity:** There are high correlations between `BILL_AMT1 ... BIL_AMT6` which introduces multicollinearity into the data. We will remove multi-collinearity by using the `remove_multicollinearity` and `multicollinearity_threshold` parameters in setup. <br/>
<br/>
- **Data Scale / Range:** Notice how the scale / range of numeric features are different. For example the `AGE` feature ranges from between 21 to 79 and `BILL_AMT1` ranges from -165,580 to 964,511. This may cause problems for algorithms that assume all features have variance within the same order. In this case, the order of magnitude for `BILL_AMT1` is widely different than `AGE`. We will deal with this problem by using the `normalize` parameter in setup. <br/>
<br/>
- **Distribution of Feature Space:** Numeric features are not normally distributed. Look at the distributions of `LIMIT_BAL`, `BILL_AMT1` and `PAY_AMT1 ... PAY_AMT6`. A few features are also highly skewed such as `PAY_AMT1`. This may cause problems for algorithms that assume normal or approximate normal distributions of the data. Examples include Logistic Regression, Linear Discriminant Analysis (LDA) and Naive Bayes.  We will deal with this problem by using the `transformation` parameter in setup. <br/>
<br/>
- **Group Features:** From the data description we know that certain features are related with each other such as `BILL_AMT1 ... BILL_AMT6` and `PAY_AMT1 ... PAY_AMT6`. We will use the `group_features` parameter in setup to extract statistical information from these features.  <br/>
<br/>
- **Bin Numeric Features:** When looking at the correlations between the numeric features and the target variable, we that `AGE` and `LIMIT_BAL` are weak. We will use the `bin_numeric_features` parameter to remove the noise from these variables which may help linear algorithms. <br/>

In [2]:
#check the shape of data
dataset.shape

(7379, 208)

In order to demonstrate the `predict_model()` function on unseen data, a sample of 1200 rows has been withheld from the original dataset to be used for predictions. This should not be confused with a train/test split as this particular split is performed to simulate a real life scenario. Another way to think about this is that these 1200 records were not available at the time when the machine learning experiment was performed.

In [3]:
data = dataset.sample(frac=0.95, random_state=786)
data_unseen = dataset.drop(data.index)

data.reset_index(inplace=True, drop=True)
data_unseen.reset_index(inplace=True, drop=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions ' + str(data_unseen.shape))

Data for Modeling: (7010, 208)
Unseen Data For Predictions (369, 208)

# 5.0 Setting up Environment in PyCaret

In the previous tutorial __[Binary Classification (CLF101) - Level Beginner](https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Beginner%20-%20%20CLF101.ipynb)__ we learned how to initialize the environment in pycaret using `setup()`. No additional parameters were passed in our last example as we did not perform any pre-processing steps. In this example we will take it to the next level by customizing the pre-processing pipeline using `setup()`. Let's look at how to implement all the steps discussed in section 4 above.

In [4]:
from pycaret.classification import *

In [5]:
data.head(10)

,Unnamed: 0,gmDate,teamAbbr,teamConf,teamDiv,teamRslt,teamDayOff,opptAbbr,opptConf,opptDiv,opptDayOff,seasonID,oppt2P%_cum_mean,opptAway2P%_cum_mean,oppt2PA_cum_mean,opptAway2PA_cum_mean,oppt2PM_cum_mean,opptAway2PM_cum_mean,oppt3P%_cum_mean,opptAway3P%_cum_mean,oppt3PA_cum_mean,opptAway3PA_cum_mean,oppt3PM_cum_mean,opptAway3PM_cum_mean,opptAR_cum_mean,opptAwayAR_cum_mean,opptASST%_cum_mean,opptAwayASST%_cum_mean,opptAST_cum_mean,opptAwayAST_cum_mean,opptAST/TO_cum_mean,opptAwayAST/TO_cum_mean,opptBLK_cum_mean,opptAwayBLK_cum_mean,opptBLK%_cum_mean,opptAwayBLK%_cum_mean,opptBLKR_cum_mean,opptAwayBLKR_cum_mean,opptDRB_cum_mean,opptAwayDRB_cum_mean,opptDREB%_cum_mean,opptAwayDREB%_cum_mean,opptDrtg_cum_mean,opptAwayDrtg_cum_mean,opptEDiff_cum_mean,opptAwayEDiff_cum_mean,opptEFG%_cum_mean,opptAwayEFG%_cum_mean,opptFG%_cum_mean,opptAwayFG%_cum_mean,opptFGA_cum_mean,opptAwayFGA_cum_mean,opptFGM_cum_mean,opptAwayFGM_cum_mean,opptFIC_cum_mean,opptAwayFIC_cum_mean,opptFIC40_cum_mean,opptAwayFIC40_cum_mean,opptFT%_cum_mean,opptAwayFT%_cum_mean,opptFTA_cum_mean,opptAwayFTA_cum_mean,opptFTM_cum_mean,opptAwayFTM_cum_mean,opptORB_cum_mean,opptAwayORB_cum_mean,opptOREB%_cum_mean,opptAwayOREB%_cum_mean,opptOrtg_cum_mean,opptAwayOrtg_cum_mean,opptPF_cum_mean,opptAwayPF_cum_mean,opptPPS_cum_mean,opptAwayPPS_cum_mean,opptPTS_cum_mean,opptAwayPTS_cum_mean,opptPTS1_cum_mean,opptAwayPTS1_cum_mean,opptPTS2_cum_mean,opptAwayPTS2_cum_mean,opptPTS3_cum_mean,opptAwayPTS3_cum_mean,opptPTS4_cum_mean,opptAwayPTS4_cum_mean,opptPTS5_cum_mean,opptAwayPTS5_cum_mean,opptPTS6_cum_mean,opptAwayPTS6_cum_mean,opptPTS7_cum_mean,opptAwayPTS7_cum_mean,opptPTS8_cum_mean,opptAwayPTS8_cum_mean,opptPlay%_cum_mean,opptAwayPlay%_cum_mean,opptSTL_cum_mean,opptAwaySTL_cum_mean,opptSTL%_cum_mean,opptAwaySTL%_cum_mean,opptSTL/TO_cum_mean,opptAwaySTL/TO_cum_mean,opptTO_cum_mean,opptAwayTO_cum_mean,opptTO%_cum_mean,opptAwayTO%_cum_mean,opptTRB_cum_mean,opptAwayTRB_cum_mean,opptTREB%_cum_mean,opptAwayTREB%_cum_mean,opptTS%_cum_mean,opptAwayTS%_cum_mean,team2P%_cum_mean,teamHome2P%_cum_mean,team2PA_cum_mean,teamHome2PA_cum_mean,team2PM_cum_mean,teamHome2PM_cum_mean,team3P%_cum_mean,teamHome3P%_cum_mean,team3PA_cum_mean,teamHome3PA_cum_mean,team3PM_cum_mean,teamHome3PM_cum_mean,teamAR_cum_mean,teamHomeAR_cum_mean,teamASST%_cum_mean,teamHomeASST%_cum_mean,teamAST_cum_mean,teamHomeAST_cum_mean,teamAST/TO_cum_mean,teamHomeAST/TO_cum_mean,teamBLK_cum_mean,teamHomeBLK_cum_mean,teamBLK%_cum_mean,teamHomeBLK%_cum_mean,teamBLKR_cum_mean,teamHomeBLKR_cum_mean,teamDRB_cum_mean,teamHomeDRB_cum_mean,teamDREB%_cum_mean,teamHomeDREB%_cum_mean,teamDrtg_cum_mean,teamHomeDrtg_cum_mean,teamEDiff_cum_mean,teamHomeEDiff_cum_mean,teamEFG%_cum_mean,teamHomeEFG%_cum_mean,teamFG%_cum_mean,teamHomeFG%_cum_mean,teamFGA_cum_mean,teamHomeFGA_cum_mean,teamFGM_cum_mean,teamHomeFGM_cum_mean,teamFIC_cum_mean,teamHomeFIC_cum_mean,teamFIC40_cum_mean,teamHomeFIC40_cum_mean,teamFT%_cum_mean,teamHomeFT%_cum_mean,teamFTA_cum_mean,teamHomeFTA_cum_mean,teamFTM_cum_mean,teamHomeFTM_cum_mean,teamORB_cum_mean,teamHomeORB_cum_mean,teamOREB%_cum_mean,teamHomeOREB%_cum_mean,teamOrtg_cum_mean,teamHomeOrtg_cum_mean,teamPF_cum_mean,teamHomePF_cum_mean,teamPPS_cum_mean,teamHomePPS_cum_mean,teamPTS_cum_mean,teamHomePTS_cum_mean,teamPTS1_cum_mean,teamHomePTS1_cum_mean,teamPTS2_cum_mean,teamHomePTS2_cum_mean,teamPTS3_cum_mean,teamHomePTS3_cum_mean,teamPTS4_cum_mean,teamHomePTS4_cum_mean,teamPTS5_cum_mean,teamHomePTS5_cum_mean,teamPTS6_cum_mean,teamHomePTS6_cum_mean,teamPTS7_cum_mean,teamHomePTS7_cum_mean,teamPTS8_cum_mean,teamHomePTS8_cum_mean,teamPlay%_cum_mean,teamHomePlay%_cum_mean,teamSTL_cum_mean,teamHomeSTL_cum_mean,teamSTL%_cum_mean,teamHomeSTL%_cum_mean,teamSTL/TO_cum_mean,teamHomeSTL/TO_cum_mean,teamTO_cum_mean,teamHomeTO_cum_mean,teamTO%_cum_mean,teamHomeTO%_cum_mean,teamTRB_cum_mean,teamHomeTRB_cum_mean,teamTREB%_cum_mean,teamHomeTREB%_cum_mean,teamTS%_cum_mean,teamHomeTS%_cum_mean
0,7284,2018-03-30,LAL,West,Pacific,0,2,MIL,East,Central,1,2017-2018,0.532839,0.526911,57.626667,57.918919,30.706667,30.486486,0.359399,0.362030,24.600000,25.081081,8.786667,9.054054,17.703560,17.289803,58.062136,56.611346,23.040000,22.594595,1.781512,1.714849,5.480000,5.027027,5.712575,5.201716,9.589608,8.728824,31.200000,31.621622,77.005188,79.182773,110.092400,109.688932,-0.217440,-1.233751,0.533875,0.530600,0.480481,0.476162,82.226667,83.000000,39.493333,39.540541,79.846667,78.280405,66.171797,64.671541,0.780212,0.774722,23.440000,22.189189,18.266667,17.108108,8.213333,8.459459,20.335789,20.817227,109.874960,108.455181,21.333333,21.675676,1.293247,1.270114,106.040000,105.243243,26.640000,26.918919,27.226667,27.162162,26.426667,25.540541,25.213333,24.729730,0.533333,0.891892,0.000000,0.000000,0.0,0.0,0.0,0.0,0.449292,0.444227,8.680000,9.027027,8.971231,9.267422,65.773107,67.073489,13.880000,14.378378,13.022292,13.399392,39.413333,40.081081,48.386076,49.026557,0.573208,0.567503,0.519139,0.524151,59.729730,60.371429,30.932432,31.542857,0.338799,0.326191,29.040541,29.057143,10.000000,9.542857,17.124534,17.603383,58.080454,59.725294,23.797297,24.600000,1.630381,1.739494,4.770270,4.971429,4.684493,4.865029,8.113081,8.364314,35.513514,37.400000,77.873953,79.529594,108.075846,103.964083,-1.368905,2.006906,0.518080,0.513434,0.461512,0.459654,88.770270,89.428571,40.932432,41.085714,80.525338,83.110714,66.492428,68.705709,0.711828,0.709043,23.256757,22.200000,16.486486,15.742857,10.756757,10.857143,23.508808,23.393957,106.706941,105.970989,21.189189,20.171429,1.223146,1.204049,108.351351,107.457143,26.756757,25.571429,28.189189,27.714286,27.054054,27.571429,25.297297,25.571429,0.932432,1.028571,0.121622,0.000000,0.0,0.0,0.0,0.0,0.436597,0.437114,7.824324,8.114286,7.711151,7.976983,53.007884,56.793580,15.716216,15.457143,13.713054,13.501186,46.270270,48.257143,50.718238,51.915451,0.547909,0.542386
1,3511,2015-03-24,DET,East,Central,1,2,TOR,East,Atlantic,2,2014-2015,0.497651,0.493124,58.700000,61.205882,29.171429,30.147059,0.349719,0.340009,25.100000,24.941176,8.814286,8.500000,16.167671,15.307447,55.058577,51.506665,20.842857,19.852941,1.805083,1.910071,4.400000,4.352941,4.658199,4.579856,7.590500,7.226156,30.714286,29.323529,74.035896,72.120124,107.614543,110.098006,3.386534,1.594165,0.506420,0.498465,0.453734,0.448856,83.800000,86.147059,37.985714,38.647059,75.491071,74.180147,62.368884,60.904035,0.788433,0.793794,24.842857,25.441176,19.557143,20.000000,10.800000,11.352941,26.306204,27.879876,111.001077,111.692171,21.014286,22.205882,1.249699,1.233335,104.342857,105.794118,25.357143,25.441176,26.671429,27.911765,25.685714,25.617647,25.671429,25.147059,0.957143,1.676471,0.000000,0.000000,0.0,0.0,0.0,0.0,0.442913,0.446221,7.614286,8.058824,8.063687,8.466729,64.138899,73.399297,12.871429,11.970588,11.943071,10.927229,41.514286,40.676471,49.302717,47.786709,0.551499,0.544335,0.465929,0.472729,61.171429,60.114286,28.357143,28.257143,0.330859,0.341337,25.071429,25.600000,8.414286,8.857143,16.177067,17.138080,57.847986,60.954260,21.242857,22.600000,1.766291,2.043283,4.614286,4.428571,4.891464,4.701123,7.670000,7.476949,32.471429,31.857143,73.663371,76.389800,106.034660,107.932146,-1.725946,-0.858297,0.476047,0.485703,0.427067,0.433909,86.242857,85.714286,36.771429,37.114286,72.580357,75.871429,59.985767,62.748206,0.708637,0.716183,22.700000,24.514286,16.057143,17.371429,12.971429,12.342857,27.718800,26.374543,104.308714,107.073849,19.042857,18.628571,1.139817,1.175554,98.014286,100.457143,24.428571,25.857143,24.042857,23.857143,24.514286,25.885714,24.085714,24.257143,0.800000,0.314286,0.142857,0.285714,0.0,0.0,0.0,0.0,0.423776,0.432440,7.642857,7.428571,8.128647,7.903023,61.208199,65.584129,13.542857,12.485714,12.311263,11.405577,45.442857,44.200000,50.475293,50.056103,0.510054,0.521537
2,4645,2016-03-09,SAC,West,Pacific,0,2,CLE,East,Central,2,2015-2016,0.509876,0.496941,55.612903,54.965517,28.306452,27.310345,0.356418,0.349303,28.161290,28.310345,10.064516,9.862069,17.207590,15.787300,58.310524,54.254062,22.419355,20.137931,1.803202,1.516707,3.661290,3.310345,3.875524,3.491979,6.717771,6.304186,34.032258,34.413793,77.881516,77.201876,103.522940,101.813407,6.525134,4.270234,0.519965,0.508031,0.459484,0.448300,83.774194,83.275862,38.370968,37.172414,77.443548,71.500000,64.062237,58.569845,0.744721,0.730010,22.193548,21.724138,16.419355,15.862069,10.774194,10.344828,25.012842,22.798124,110.048074,106.083641,20.500000,21.068966,1.238871,1.208131,103.225806,100.068966,25.661290,25.275862,26.129032,25.724138,25.677419,24.413793,24.951613,22.931034,0.661290,1.413793,0.145161,0.310345,0.0,0.0,0.0,0.0,0.444166,0.428766,6.870968,6.896552,7.286603,7.294497,55.163208,52.801862,13.629032,13.931034,12.695890,13.065866,44.806452,44.758621,52.242139,51.334000,0.553513,0.540931,0.503202,0.503037,63.790323,63.000000,31.983871,31.600000,0.357247,0.352383,22.645161,22.600000,8.080645,7.966667,17.808184,17.223810,62.364161,61.008600,24.903226,24.000000,1.575469,1.490483,4.403226,3.800000,4.345981,3.731053,6.977202,6.125050,34.209677,34.300000,76.931065,77.059020,108.332500,107.092967,-2.470353,-1.374403,0.511642,0.510043,0.464379,0.462677,86.435484,85.600000,40.064516,39.566667,79.885081,78.033333,66.013419,64.541670,0.717521,0.713373,25.854839,27.133333,18.677419,19.533333,10.741935,11.066667,23.997310,24.859620,105.862147,105.718563,20.661290,19.900000,1.244073,1.253583,106.887097,106.633333,27.048387,26.966667,26.516129,25.766667,26.048387,26.933333,26.612903,26.533333,0.403226,0.300000,0.258065,0.133333,0.0,0.0,0.0,0.0,0.434050,0.431210,8.822581,8.300000,8.708532,8.208563,55.611427,50.782187,16.677419,17.166667,14.581548,15.008823,44.951613,45.366667,50.320532,51.052507,0.547527,0.547520
3,4741,2016-03-22,NO,West,Southwest,0,2,MIA,East,Southeast,3,2015-2016,0.505893,0.489188,62.971014,64.060606,31.753623,31.333333,0.332657,0.321588,18.086957,17.454545,6.101449,5.848485,16.419051,16.866042,54.965113,57.892394,20.855072,21.575758,1.602801,1.597282,6.623188,6.575758,7.009442,7.010855,10.701436,10.426494,34.608696,34.696970,78.712804,78.644948,104.043552,104.229012,1.365926,-1.891721,0.506920,0.493079,0.468700,0.456706,81.057971,81.515152,37.855072,37.181818,76.190217,73.742424,63.100761,61.150658,0.750254,0.757403,23.463768,20.909091,17.507246,15.848485,9.623188,9.454545,22.117655,21.355052,105.409478,102.337291,18.115942,17.151515,1.231814,1.182618,99.318841,96.060606,24.695652,23.787879,24.782609,24.666667,23.956522,23.242424,25.144928,23.939394,0.739130,0.424242,0.000000,0.000000,0.0,0.0,0.0,0.0,0.442400,0.428597,6.637681,6.333333,7.011667,6.690876,51.886933,46.984639,14.173913,14.727273,13.459930,13.985506,44.231884,44.151515,51.657306,51.436348,0.545329,0.530139,0.484430,0.489441,62.043478,61.882353,30.000000,30.235294,0.352138,0.389303,24.275362,24.735294,8.608696,9.617647,16.657975,17.958847,56.829516,60.039738,21.913043,23.823529,1.879310,2.101485,4.565217,5.088235,4.705257,5.272385,7.535039,8.370868,33.231884,32.794118,79.154920,79.449609,109.120080,109.669497,-3.194074,0.398947,0.498042,0.516785,0.448103,0.461074,86.318841,86.617647,38.608696,39.852941,75.057971,82.238971,62.212048,68.335062,0.784093,0.788612,22.347826,22.264706,17.449275,17.352941,9.463768,9.794118,21.534184,21.948868,105.926006,110.068444,21.086957,20.441176,1.202641,1.237138,103.275362,106.676471,26.086957,27.117647,25.637681,26.558824,25.275362,26.117647,25.637681,26.617647,0.637681,0.264706,0.000000,0.000000,0.0,0.0,0.0,0.0,0.429439,0.447379,7.826087,8.205882,7.992806,8.397894,64.747119,68.424397,13.246377,12.411765,12.060003,11.348015,42.695652,42.588235,48.876839,49.429091,0.537859,0.553921
4,3463,2015-03-18,PHI,East,Atlantic,1,2,DET,East,Central,1,2014-2015,0.466933,0.462261,61.089552,62.212121,28.373134,28.636364,0.329599,0.319982,25.029851,24.454545,8.373134,7.939394,16.112315,15.207400,57.643509,54.313709,21.149254,19.818182,1.700390,1.497309,4.477612,4.575758,4.753779,4.865873,7.468085,7.516470,32.194030,32.727273,73.563646,70.840303,106.356039,104.499370,-2.001124,-2.618439,0.476261,0.468482,0.427434,0.422430,86.119403,86.666667,36.746269,36.575758,72.186567,69.098485,59.736521,57.238424,0.706118,0.698288,22.835821,20.666667,16.134328,14.575758,13.029851,13.545455,27.931724,29.159697,104.354915,101.880930,19.014925,19.454545,1.141422,1.106661,98.000000,95.666667,24.373134,22.969697,24.417910,24.696970,24.358209,23.090909,24.119403,24.060606,0.582090,0.848485,0.149254,0.000000,0.0,0.0,0.0,0.0,0.424043,0.417439,7.656716,7.939394,8.141975,8.449130,59.394257,57.847597,13.611940,14.515152,12.387096,13.175915,45.223881,46.272727,50.452207,50.841591,0.510339,0.500170,0.449291,0.465006,56.283582,56.323529,25.328358,26.205882,0.309878,0.319197,25.462687,25.941176,8.044776,8.382353,15.635900,17.156247,61.419581,66.244953,20.582090,22.911765,1.209769,1.384871,6.000000,6.588235,6.237173,6.840541,10.869669,12.046803,31.298507,32.147059,72.954388,74.079818,104.418143,102.808094,-10.176487,-4.970176,0.458775,0.474074,0.409272,0.422718,81.746269,82.264706,33.373134,34.588235,63.229478,69.878676,52.309442,57.877015,0.677846,0.705556,23.985075,24.205882,16.164179,17.058824,11.641791,11.382353,26.382870,24.614191,94.241657,97.837918,21.313433,21.852941,1.117210,1.159753,90.955224,94.617647,22.238806,24.176471,22.656716,23.058824,23.208955,23.029412,22.477612,24.088235,0.373134,0.264706,0.000000,0.000000,0.0,0.0,0.0,0.0,0.378434,0.391409,9.746269,9.647059,10.103976,9.960015,57.157112,58.683779,18.208955,17.676471,16.485782,16.017844,42.940299,43.529412,48.169725,49.048065,0.494037,0.511841
5,661,2013-01-28,CHI,East,Central,1,2,CHA,East,Southeast,2,2012-2013,0.441914,0.437247,65.581395,65.473684,29.093023,28.789474,0.351256,0.335158,16.232558,16.631579,5.697674,5.578947,14.963977,13.791289,54.774965,50.485695,19.069767,17.263158,1.388535,1.335695,6.534884,5.736842,7.020091,6.234768,10.079186,8.840232,29.558140,29.105263,71.070288,69.851747,111.202621,113.925926,-8.818902,-12.052489,0.460074,0.452658,0.425321,0.418679,81.813953,82.105263,34.790698,34.368421,66.494186,63.546053,54.772702,52.135484,0.753621,0.729100,26.418605,26.157895,19.837209,18.894737,11.581395,12.631579,27.435342,30.148253,102.383719,101.873437,19.697674,19.894737,1.164716,1.137058,95.116279,93.210526,22.302326,21.578947,24.604651,24.947368,23.651163,21.789474,23.441860,23.421053,0.906977,1.000000,0.209302,0.473684,0.0,0.0,0.0,0.0,0.412195,0.413837,7.348837,7.842105,7.857444,8.494905,52.799798,58.962458,14.209302,13.631579,13.201916,12.760911,41.139535,41.736842,48.050007,47.661716,0.509312,0.497847,0.457102,0.434312,67.441860,68.960000,30.627907,29.840000,0.359842,0.389344,13.302326,13.080000,4.744186,5.080000,17.658721,17.660368,64.139258,65.370532,22.720930,22.840000,1.642202,1.684240,5.325581,6.440000,5.932556,7.211396,7.934065,9.430368,31.534884,31.800000,73.318923,72.960956,100.698030,98.355844,2.519251,3.845352,0.470202,0.458444,0.440756,0.427540,80.744186,82.040000,35.372093,34.920000,70.645349,71.260000,58.361947,59.200556,0.781044,0.774920,22.837209,21.760000,17.860465,16.920000,12.395349,13.080000,28.820205,30.718344,103.217281,102.201196,19.813953,19.400000,1.165814,1.128028,93.348837,91.840000,24.209302,23.200000,22.441860,22.640000,23.186047,23.000000,22.651163,22.760000,0.860465,0.240000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.425660,0.418644,7.139535,7.160000,7.885453,7.931756,51.339670,52.912040,14.906977,14.560000,14.123091,13.720048,43.930233,44.880000,51.815000,52.053256,0.516042,0.503152
6,6704,2018-01-03,WAS,East,Southeast,1,3,NY,East,Atlantic,0,2017-2018,0.503724,0.486440,64.324324,67.066667,32.162162,32.533333,0.352746,0.308627,21.675676,20.733333,7.675676,6.600000,17.055051,17.892467,57.010843,61.808480,22.756757,24.266667,1.587608,1.730940,4.891892,4.866667,5.089073,4.997227,7.779584,7.437420,33.756757,33.066667,76.059278,75.653653,107.633600,110.263893,-0.156903,-9.317560,0.511243,0.484327,0.465778,0.446600,86.000000,87.800000,39.837838,39.133333,76.422297,71.900000,63.470597,59.849127,0.798819,0.799193,19.972973,17.200000,15.918919,13.600000,10.918919,10.600000,25.930727,24.346347,107.476697,100.946333,20.783784,19.733333,1.212308,1.124240,103.270270,98.466667,26.216216,25.800000,25.243243,23.866667,25.081081,23.866667,26.351351,24.933333,0.378378,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.441408,0.421867,6.972973,6.600000,7.249100,6.779093,47.981405,47.679080,15.324324,15.533333,13.945868,13.998420,44.675676,43.666667,52.058227,50.868040,0.547668,0.517267,0.502278,0.535094,59.621622,57.944444,29.783784,30.944444,0.364835,0.363517,26.594595,27.944444,9.783784,10.277778,17.002195,17.393044,57.120114,56.645356,22.702703,23.333333,1.765722,1.690589,4.324324,5.166667,4.384595,5.216906,7.267124,8.879267,33.405405,34.722222,77.821746,79.325689,106.385008,105.308750,2.299824,6.387011,0.516616,0.540561,0.459708,0.480872,86.216216,85.888889,39.567568,41.222222,78.307432,84.250000,64.849378,70.125617,0.756865,0.771572,22.783784,22.555556,17.351351,17.333333,10.000000,10.166667,24.030170,24.481028,108.684832,111.695761,21.729730,21.722222,1.236630,1.285628,106.270270,110.055556,27.405405,28.777778,26.405405,26.722222,26.027027,27.555556,25.972973,27.000000,0.459459,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.439586,0.455561,7.810811,8.000000,7.974765,8.103256,59.549573,55.737111,13.783784,14.777778,12.527989,13.358417,43.405405,44.888889,49.958903,52.573828,0.553059,0.575172
7,5549,2017-01-18,HOU,West,Southwest,1,1,MIL,East,Central,2,2016-2017,0.519593,0.511756,60.250000,59.277778,31.175000,30.333333,0.376245,0.365161,23.125000,23.833333,8.575000,8.500000,18.792552,19.009289,62.325620,63.761694,24.850000,24.888889,1.960425,1.985689,5.500000,5.055556,5.751752,5.413061,9.408658,8.754056,33.025000,33.111111,77.311355,76.913356,108.452825,108.910811,1.632127,-1.466367,0.530128,0.520778,0.478208,0.469089,83.375000,83.111111,39.750000,38.833333,83.062500,79.208333,68.890000,65.756511,0.756607,0.757872,22.400000,19.222222,17.075000,14.555556,9.400000,9.833333,22.671482,23.086644,110.084952,107.444444,20.000000,19.500000,1.268535,1.218406,105.150000,100.722222,27.925000,27.277778,25.500000,23.777778,26.450000,25.611111,25.050000,24.000000,0.225000,0.055556,0.000000,0.000000,0.0,0.0,0.0,0.0,0.454213,0.446200,8.125000,7.388889,8.452535,7.855461,61.198413,56.724000,13.800000,14.222222,12.852635,13.352217,42.425000,42.944444,49.990808,49.412067,0.565110,0.551250,0.550611,0.559385,46.840909,45.950000,25.704545,25.550000,0.371961,0.370690,39.954545,40.750000,14.840909,15.100000,18.384789,18.669185,63.015736,64.005130,25.568182,26.100000,1.823500,1.947410,4.477273,4.600000,4.513236,4.632210,9.639850,10.213450,33.454545,34.600000,76.482757,77.985280,108.433736,105.878650,6.865891,10.688245,0.554070,0.556625,0.468143,0.469240,86.795455,86.700000,40.545455,40.650000,89.093750,93.087500,73.745666,77.462330,0.757305,0.763410,24.613636,25.500000,18.659091,19.500000,10.977273,11.250000,25.214736,25.749205,115.299627,116.566895,19.704545,18.250000,1.325264,1.340335,114.590909,115.900000,30.681818,31.250000,28.795455,28.450000,28.659091,30.500000,25.659091,25.700000,0.590909,0.000000,0.204545,0.000000,0.0,0.0,0.0,0.0,0.444559,0.448590,8.090909,8.100000,8.064159,8.067710,55.801355,59.039620,15.522727,15.100000,13.703895,13.341815,44.431818,45.850000,50.988377,51.923150,0.588032,0.592510

In [6]:
data.columns.to_list()

['Unnamed: 0',
 'gmDate',
 'teamAbbr',
 'teamConf',
 'teamDiv',
 'teamRslt',
 'teamDayOff',
 'opptAbbr',
 'opptConf',
 'opptDiv',
 'opptDayOff',
 'seasonID',
 'oppt2P%_cum_mean',
 'opptAway2P%_cum_mean',
 'oppt2PA_cum_mean',
 'opptAway2PA_cum_mean',
 'oppt2PM_cum_mean',
 'opptAway2PM_cum_mean',
 'oppt3P%_cum_mean',
 'opptAway3P%_cum_mean',
 'oppt3PA_cum_mean',
 'opptAway3PA_cum_mean',
 'oppt3PM_cum_mean',
 'opptAway3PM_cum_mean',
 'opptAR_cum_mean',
 'opptAwayAR_cum_mean',
 'opptASST%_cum_mean',
 'opptAwayASST%_cum_mean',
 'opptAST_cum_mean',
 'opptAwayAST_cum_mean',
 'opptAST/TO_cum_mean',
 'opptAwayAST/TO_cum_mean',
 'opptBLK_cum_mean',
 'opptAwayBLK_cum_mean',
 'opptBLK%_cum_mean',
 'opptAwayBLK%_cum_mean',
 'opptBLKR_cum_mean',
 'opptAwayBLKR_cum_mean',
 'opptDRB_cum_mean',
 'opptAwayDRB_cum_mean',
 'opptDREB%_cum_mean',
 'opptAwayDREB%_cum_mean',
 'opptDrtg_cum_mean',
 'opptAwayDrtg_cum_mean',
 'opptEDiff_cum_mean',
 'opptAwayEDiff_cum_mean',
 'opptEFG%_cum_mean',
 'opptAwayEFG%_cum_mean',
 'opptFG%_cum_mean',
 'opptAwayFG%_cum_mean',
 'opptFGA_cum_mean',
 'opptAwayFGA_cum_mean',
 'opptFGM_cum_mean',
 'opptAwayFGM_cum_mean',
 'opptFIC_cum_mean',
 'opptAwayFIC_cum_mean',
 'opptFIC40_cum_mean',
 'opptAwayFIC40_cum_mean',
 'opptFT%_cum_mean',
 'opptAwayFT%_cum_mean',
 'opptFTA_cum_mean',
 'opptAwayFTA_cum_mean',
 'opptFTM_cum_mean',
 'opptAwayFTM_cum_mean',
 'opptORB_cum_mean',
 'opptAwayORB_cum_mean',
 'opptOREB%_cum_mean',
 'opptAwayOREB%_cum_mean',
 'opptOrtg_cum_mean',
 'opptAwayOrtg_cum_mean',
 'opptPF_cum_mean',
 'opptAwayPF_cum_mean',
 'opptPPS_cum_mean',
 'opptAwayPPS_cum_mean',
 'opptPTS_cum_mean',
 'opptAwayPTS_cum_mean',
 'opptPTS1_cum_mean',
 'opptAwayPTS1_cum_mean',
 'opptPTS2_cum_mean',
 'opptAwayPTS2_cum_mean',
 'opptPTS3_cum_mean',
 'opptAwayPTS3_cum_mean',
 'opptPTS4_cum_mean',
 'opptAwayPTS4_cum_mean',
 'opptPTS5_cum_mean',
 'opptAwayPTS5_cum_mean',
 'opptPTS6_cum_mean',
 'opptAwayPTS6_cum_mean',
 'opptPTS7_cum_mean',
 'opptAwayPTS7_cum_mean',
 'opptPTS8_cum_mean',
 'opptAwayPTS8_cum_mean',
 'opptPlay%_cum_mean',
 'opptAwayPlay%_cum_mean',
 'opptSTL_cum_mean',
 'opptAwaySTL_cum_mean',
 'opptSTL%_cum_mean',
 'opptAwaySTL%_cum_mean',
 'opptSTL/TO_cum_mean',
 'opptAwaySTL/TO_cum_mean',
 'opptTO_cum_mean',
 'opptAwayTO_cum_mean',
 'opptTO%_cum_mean',
 'opptAwayTO%_cum_mean',
 'opptTRB_cum_mean',
 'opptAwayTRB_cum_mean',
 'opptTREB%_cum_mean',
 'opptAwayTREB%_cum_mean',
 'opptTS%_cum_mean',
 'opptAwayTS%_cum_mean',
 'team2P%_cum_mean',
 'teamHome2P%_cum_mean',
 'team2PA_cum_mean',
 'teamHome2PA_cum_mean',
 'team2PM_cum_mean',
 'teamHome2PM_cum_mean',
 'team3P%_cum_mean',
 'teamHome3P%_cum_mean',
 'team3PA_cum_mean',
 'teamHome3PA_cum_mean',
 'team3PM_cum_mean',
 'teamHome3PM_cum_mean',
 'teamAR_cum_mean',
 'teamHomeAR_cum_mean',
 'teamASST%_cum_mean',
 'teamHomeASST%_cum_mean',
 'teamAST_cum_mean',
 'teamHomeAST_cum_mean',
 'teamAST/TO_cum_mean',
 'teamHomeAST/TO_cum_mean',
 'teamBLK_cum_mean',
 'teamHomeBLK_cum_mean',
 'teamBLK%_cum_mean',
 'teamHomeBLK%_cum_mean',
 'teamBLKR_cum_mean',
 'teamHomeBLKR_cum_mean',
 'teamDRB_cum_mean',
 'teamHomeDRB_cum_mean',
 'teamDREB%_cum_mean',
 'teamHomeDREB%_cum_mean',
 'teamDrtg_cum_mean',
 'teamHomeDrtg_cum_mean',
 'teamEDiff_cum_mean',
 'teamHomeEDiff_cum_mean',
 'teamEFG%_cum_mean',
 'teamHomeEFG%_cum_mean',
 'teamFG%_cum_mean',
 'teamHomeFG%_cum_mean',
 'teamFGA_cum_mean',
 'teamHomeFGA_cum_mean',
 'teamFGM_cum_mean',
 'teamHomeFGM_cum_mean',
 'teamFIC_cum_mean',
 'teamHomeFIC_cum_mean',
 'teamFIC40_cum_mean',
 'teamHomeFIC40_cum_mean',
 'teamFT%_cum_mean',
 'teamHomeFT%_cum_mean',
 'teamFTA_cum_mean',
 'teamHomeFTA_cum_mean',
 'teamFTM_cum_mean',
 'teamHomeFTM_cum_mean',
 'teamORB_cum_mean',
 'teamHomeORB_cum_mean',
 'teamOREB%_cum_mean',
 'teamHomeOREB%_cum_mean',
 'teamOrtg_cum_mean',
 'teamHomeOrtg_cum_mean',
 'teamPF_cum_mean',
 'teamHomePF_cum_mean',
 'teamPPS_cum_mean',
 'teamHomePPS_cum_mean',
 'teamPTS_cum_mean',
 'teamHomePTS_cum_mean',
 'teamPTS1_cum_mean',
 'teamHomePTS1_cum_mean',
 'teamPTS2_cum_mean',
 'teamHomePTS2_cum_mean',
 'teamPTS3_cum_mean',
 'teamHomePTS3_cum_mean',
 'teamPTS4_cum_mean',
 'teamHomePTS4_cum_mean',
 'teamPTS5_cum_mean',
 'teamHomePTS5_cum_mean',
 'teamPTS6_cum_mean',
 'teamHomePTS6_cum_mean',
 'teamPTS7_cum_mean',
 'teamHomePTS7_cum_mean',
 'teamPTS8_cum_mean',
 'teamHomePTS8_cum_mean',
 'teamPlay%_cum_mean',
 'teamHomePlay%_cum_mean',
 'teamSTL_cum_mean',
 'teamHomeSTL_cum_mean',
 'teamSTL%_cum_mean',
 'teamHomeSTL%_cum_mean',
 'teamSTL/TO_cum_mean',
 'teamHomeSTL/TO_cum_mean',
 'teamTO_cum_mean',
 'teamHomeTO_cum_mean',
 'teamTO%_cum_mean',
 'teamHomeTO%_cum_mean',
 'teamTRB_cum_mean',
 'teamHomeTRB_cum_mean',
 'teamTREB%_cum_mean',
 'teamHomeTREB%_cum_mean',
 'teamTS%_cum_mean',
 'teamHomeTS%_cum_mean']

In [7]:
data.dtypes.unique()

array([dtype('int64'), dtype('O'), dtype('float64')], dtype=object)

In [8]:
num_col_list = list(data.columns)
num_col_list.remove('teamRslt')
num_col_list.remove('teamConf')
num_col_list.remove('opptConf')
num_col_list.remove('teamAbbr')
num_col_list.remove('opptAbbr')
num_col_list.remove('teamDiv')
num_col_list.remove('opptDiv')
num_col_list.remove('seasonID')
num_col_list.remove('gmDate')

In [26]:
# from mlflow import log_metric, log_param, log_artifacts

In [27]:
# data['gmDate'] = data['gmDate'].astype('string')

In [28]:
# list_season=data["seasonID"].unique()
# list_season = sorted(list_season)
# list_date =data["gmDate"].unique()
# list_date = sorted(list_date)

In [29]:
# ordinal_dict = {"seasonID" : list_season, "gmDate" : list_date}

In [30]:
# # col_list = dataframe.columns.to_list()
# group_list1 = [ ["team"+x[4:],"oppt"+x[4:]] for x in num_col_list if x[:4] == "team" and x[4:8]!="Home"]
# group_list2 = [ ["team"+"Home"+x[8:],"oppt"+"Away"+x[8:]] for x in num_col_list if x[:4] == "team" and x[4:8]=="Home"]
# group_list = group_list1 + group_list2

In [31]:
# exp_clf102 = setup(data = data, target = 'teamRslt', session_id=123,
#                   normalize = True, 
#                   transformation = False, 
#                   ignore_low_variance = False,
#                   remove_multicollinearity = True, multicollinearity_threshold = 0.95,
#                   numeric_features = num_col_list,
#                   categorical_features = ['teamConf', 'opptConf', 'teamAbbr', 'opptAbbr',  'teamDiv' , 'opptDiv'],
#                   ordinal_features = ordinal_dict,
#                    data_split_stratify = True,
#                    pca = False,
#                    feature_selection = True,
#                    fix_imbalance = False)
#                    #group_features = group_list)
# #                   log_experiment = True, experiment_name = 'test1')

In [32]:
# exp_clf102

# Feature Selection only Starting point

In [9]:
exp_clf102 = setup(data = data, target = 'teamRslt', session_id=123,
                  normalize = False, 
                  transformation = False, 
                  ignore_low_variance = False,
                  remove_multicollinearity = False, multicollinearity_threshold = 0.95,
                  numeric_features = num_col_list,
                  categorical_features = ['teamConf', 'opptConf', 'teamAbbr', 'opptAbbr',  'teamDiv' , 'opptDiv'],
#                   ordinal_features = ordinal_dict,
                   data_split_stratify = False,
                   pca = False,
                   feature_selection = True,
                   fix_imbalance = False)
                   #group_features = group_list)
#                   log_experiment = True, experiment_name = 'test1')

In [13]:
exp_clf102

(False,
 False,
 False,
 [<pandas.io.formats.style.Styler at 0x293f6d09730>,
                                      Model  Accuracy     AUC  Recall   Prec.  \
  et                 Extra Trees Classifier    0.6508  0.6795  0.7776  0.6773
  catboost              CatBoost Classifier    0.6508  0.6843  0.7787  0.6769
  gbc          Gradient Boosting Classifier    0.6468  0.6833  0.7755  0.6737
  ridge                    Ridge Classifier    0.6419  0.0000  0.7683  0.6709
  rf               Random Forest Classifier    0.6419  0.6777  0.7645  0.6723
  lightgbm  Light Gradient Boosting Machine    0.6408  0.6656  0.7516  0.6751
  lda          Linear Discriminant Analysis    0.6392  0.6686  0.7582  0.6712
  ada                  Ada Boost Classifier    0.6315  0.6540  0.7509  0.6658
  xgboost         Extreme Gradient Boosting    0.6303  0.6536  0.7364  0.6689
  nb                            Naive Bayes    0.6042  0.6623  0.5674  0.7055
  knn                K Neighbors Classifier    0.5823  0.5757  0.6997  0.6308
  dt               Decision Tree Classifier    0.5807  0.5665  0.6467  0.6433
  svm                   SVM - Linear Kernel    0.5721  0.0000  0.5633  0.7243
  qda       Quadratic Discriminant Analysis    0.4998  0.4975  0.5101  0.5857
  lr                    Logistic Regression    0.0000  0.0000  0.0000  0.0000

                F1   Kappa     MCC  TT (Sec)
  et        0.7237  0.2552  0.2602     0.162
  catboost  0.7240  0.2549  0.2599     9.310
  gbc       0.7209  0.2461  0.2510     1.952
  ridge     0.7161  0.2368  0.2412     0.021
  rf        0.7153  0.2379  0.2416     0.307
  lightgbm  0.7111  0.2399  0.2426     0.408
  lda       0.7119  0.2339  0.2374     0.187
  ada       0.7056  0.2175  0.2206     0.412
  xgboost   0.7009  0.2196  0.2214     1.704
  nb        0.6242  0.2157  0.2237     0.020
  knn       0.6633  0.1171  0.1185     0.059
  dt        0.6447  0.1331  0.1333     0.103
  svm       0.5465  0.1434  0.1861     0.078
  qda       0.5430 -0.0048 -0.0052     0.052
  lr        0.0000  0.0000  0.0000     0.700  ],
 123,
 None,
 [('Setup Config',
                                  Description             Value
   0                               session_id               123
   1                                   Target          teamRslt
   2                              Target Type            Binary
   3                            Label Encoded        0: 0, 1: 1
   4                            Original Data       (7010, 208)
   5                           Missing Values             False
   6                         Numeric Features               199
   7                     Categorical Features                 7
   8                         Ordinal Features             False
   9                High Cardinality Features             False
   10                 High Cardinality Method              None
   11                   Transformed Train Set       (4906, 289)
   12                    Transformed Test Set       (2104, 289)
   13                      Shuffle Train-Test              True
   14                     Stratify Train-Test             False
   15                          Fold Generator   StratifiedKFold
   16                             Fold Number                10
   17                                CPU Jobs                -1
   18                                 Use GPU             False
   19                          Log Experiment             False
   20                         Experiment Name  clf-default-name
   21                                     USI              0cb4
   22                         Imputation Type            simple
   23          Iterative Imputation Iteration              None
   24                         Numeric Imputer              mean
   25      Iterative Imputation Numeric Model              None
   26                     Categorical Imputer          constant
   27  Iterative Imputation Categorical Model              None
   28           Unknown Categoricals Handling    least_frequent
   29                               Normalize             False
   30                        Normalize Method              None
   31                          Transformation             False
   32                   Transformation Method              None
   33                                     PCA             False
   34                              PCA Method              None
   35                          PCA Components              None
   36                     Ignore Low Variance             False
   37                     Combine Rare Levels             False
   38                    Rare Level Threshold              None
   39                         Numeric Binning             False
   40                         Remove Outliers             False
   41                      Outliers Threshold              None
   42                Remove Multicollinearity             False
   43             Multicollinearity Threshold              None
   44                              Clustering             False
   45                    Clustering Iteration              None
   46                     Polynomial Features             False
   47                       Polynomial Degree              None
   48                    Trignometry Features             False
   49                    Polynomial Threshold              None
   50                          Group Features             False
   51                       Feature Selection              True
   52            Features Selection Threshold               0.8
   53                     Feature Interaction             False
   54                           Feature Ratio             False
   55                   Interaction Threshold              None
   56                           Fix Imbalance             False
   57                    Fix Imbalance Method             SMOTE),
  ('X_training Set',
         teamHomePTS1_cum_mean  opptAbbr_MIL  opptAway2PA_cum_mean  \
   4141              24.421053           0.0             51.666668
   6759              28.208334           0.0             63.538460
   3597              25.000000           0.0             57.750000
   6076              26.392857           0.0             64.481483
   2857              25.913044           0.0             61.227272
   ...                     ...           ...                   ...
   5218              22.411764           0.0             70.352943
   4060              23.000000           0.0             65.199997
   1346              27.218750           0.0             61.235294
   3454              25.973684           0.0             64.868423
   3582              25.785715           0.0             66.666664

         teamHomeSTL%_cum_mean  opptAST_cum_mean  opptAwayPTS7_cum_mean  \
   4141               6.651126         22.270269                    0.0
   6759               8.621171         21.240000                    0.0
   3597               9.659233         20.289474                    0.0
   6076              11.131196         18.946428                    0.0
   2857               7.569335         21.181818                    0.0
   ...                     ...               ...                    ...
   5218               5.892376         22.333334                    0.0
   4060               8.627913         25.000000                    0.0
   1346               7.817991         23.904762                    0.0
   3454               7.498937         24.051283                    0.0
   3582              10.314400         20.708334                    0.0

         teamAST_cum_mean  teamHomePPS_cum_mean  seasonID_2013-2014  \
   4141         20.545454              1.218553                 0.0
   6759         22.448980              1.248875                 0.0
   3597         22.945946              1.200083                 0.0
   6076         23.275862              1.271800                 0.0
   2857         20.883720              1.246365                 0.0
   ...                ...                   ...                 ...
   5218         20.717949              1.131706                 0.0
   4060         21.066668              1.123853                 0.0
   1346         20.640625              1.276691                 0.0
   3454         20.935898              1.182100                 0.0
   3582         23.799999              1.420157                 1.0

         opptAbbr_UTA  ...  opptFG%_cum_mean  teamHomeDrtg_cum_mean  \
   4141           0.0  ...          0.452876             105.135872
   6759           0.0  ...          0.455400             103.887230
   3597           0.0  ...          0.444839             103.462196
   6076           0.0  ...          0.420421             100.868484
   2857           0.0  ...          0.425902             103.301605
   ...            ...  ...               ...                    ...
   5218           0.0  ...          0.435008             102.561699
   4060           0.0  ...          0.470378             106.701744
   1346           0.0  ...          0.473954             105.681892
   3454           0.0  ...          0.467346             107.574234
   3582           0.0  ...          0.435379             104.670128

         teamTO%_cum_mean  teamHomeFTA_cum_mean  opptAbbr_PHI  teamAbbr_MIN  \
   4141         12.012391             27.789474           0.0           0.0
   6759         13.087386             21.291666           0.0           0.0
   3597         14.204065             20.166666           0.0           0.0
   6076         14.107163             22.357143           0.0           0.0
   2857         11.755393             23.652174           0.0           0.0
   ...                ...                   ...           ...           ...
   5218         13.195215             21.823530           0.0           0.0
   4060         14.485440             17.000000           0.0           0.0
   1346         13.274402             26.468750           0.0           0.0
   3454         13.041382             23.000000           0.0           0.0
   3582         15.231356             26.571428           0.0           0.0

         opptASST%_cum_mean  opptAR_cum_mean  teamBLKR_cum_mean  gmDate_month_10
   4141           58.971642        17.178465           7.747330              0.0
   6759           53.723583        16.360561           8.764494              0.0
   3597           57.282185        16.196383           8.823249              0.0
   6076           55.133949        14.913443           9.791583              0.0
   2857           58.032440        16.113928           7.656028              0.0
   ...                  ...              ...                ...              ...
   5218           59.977970        16.533958           7.526844              0.0
   4060           63.964149        18.858496           6.298007              0.0
   1346           60.084698        18.144236           8.619126              0.0
   3454           62.578762        18.322199           6.814507              0.0
   3582           56.782417        15.911391           9.442596              0.0

   [4906 rows x 289 columns]),
  ('y_training Set',
   4141    0
   6759    1
   3597    1
   6076    1
   2857    1
          ..
   5218    0
   4060    0
   1346    1
   3454    1
   3582    1
   Name: teamRslt, Length: 4906, dtype: int32),
  ('X_test Set',
         teamHomePTS1_cum_mean  opptAbbr_MIL  opptAway2PA_cum_mean  \
   5193              26.200001           0.0             58.000000
   3197              24.783783           0.0             53.459461
   2499              28.321428           0.0             62.259258
   1859              24.799999           0.0             61.833332
   5666              25.799999           0.0             64.687500
   ...                     ...           ...                   ...
   2694              30.000000           0.0             53.714287
   3253              23.904762           0.0             62.136364
   2318              27.575001           0.0             57.400002
   1139              28.275862           0.0             60.866665
   4849              25.600000           0.0             60.357143

         teamHomeSTL%_cum_mean  opptAST_cum_mean  opptAwayPTS7_cum_mean  \
   5193               8.398680         21.163265                    0.0
   3197               7.779978         21.298702                    0.0
   2499               9.095328         20.263159                    0.0
   1859               7.365260         22.150000                    0.0
   5666               7.281500         19.093750                    0.0
   ...                     ...               ...                    ...
   2694               8.817266         23.923077                    0.0
   3253               9.635867         20.292683                    0.0
   2318               8.397873         23.691359                    0.0
   1139               8.409242         21.350000                    0.0
   4849               9.977674         22.178572                    0.0

         teamAST_cum_mean  teamHomePPS_cum_mean  seasonID_2013-2014  \
   5193         22.941177              1.319652                 0.0
   3197         23.818182              1.221603                 0.0
   2499         24.762712              1.171079                 0.0
   1859         20.421053              1.213530                 0.0
   5666         20.281250              1.292100                 1.0
   ...                ...                   ...                 ...
   2694         21.666666              1.310350                 0.0
   3253         20.609756              1.204843                 0.0
   2318         22.506172              1.258672                 0.0
   1139         23.278688              1.219748                 1.0
   4849         20.666666              1.238180                 0.0

         opptAbbr_UTA  ...  opptFG%_cum_mean  teamHomeDrtg_cum_mean  \
   5193           0.0  ...          0.441357             105.677170
   3197           0.0  ...          0.445599             106.555351
   2499           0.0  ...          0.461589              99.669312
   1859           0.0  ...          0.458840             107.811409
   5666           0.0  ...          0.424466             109.880737
   ...            ...  ...               ...                    ...
   2694           0.0  ...          0.446192             103.788300
   3253           0.0  ...          0.441939             106.141525
   2318           0.0  ...          0.452441             105.694160
   1139           0.0  ...          0.442933             101.769920
   4849           0.0  ...          0.435264             103.147568

         teamTO%_cum_mean  teamHomeFTA_cum_mean  opptAbbr_PHI  teamAbbr_MIN  \
   5193         14.785314             26.639999           0.0           0.0
   3197         15.075710             22.000000           0.0           0.0
   2499         12.467488             23.107143           0.0           0.0
   1859         13.843605             28.200001           0.0           1.0
   5666         14.215390             28.466667           0.0           0.0
   ...                ...                   ...           ...           ...
   2694         13.490684             25.333334           0.0           1.0
   3253         12.773720             26.714285           0.0           0.0
   2318         12.760471             21.650000           0.0           0.0
   1139         12.070682             28.482759           0.0           1.0
   4849         15.139970             23.733334           0.0           0.0

         opptASST%_cum_mean  opptAR_cum_mean  teamBLKR_cum_mean  gmDate_month_10
   5193           58.509708        16.495638           7.458863              0.0
   3197           56.344521        15.866385           9.699630              0.0
   2499           54.665535        16.133429           6.601375              0.0
   1859           59.578957        16.904270           7.499953              0.0
   5666           52.616856        14.639972           6.844663              0.0
   ...                  ...              ...                ...              ...
   2694           62.793961        18.041262           8.488833              0.0
   3253           55.097393        15.863025           6.695637              0.0
   2318           61.905113        17.481873           8.183832              0.0
   1139           58.864872        16.573023           5.474500              0.0
   4849           60.504555        16.751265           6.876163              0.0

   [2104 rows x 289 columns]),
  ('y_test Set',
   5193    1
   3197    0
   2499    1
   1859    0
   5666    1
          ..
   2694    0
   3253    1
   2318    1
   1139    0
   4849    0
   Name: teamRslt, Length: 2104, dtype: int64),
  ('Transformation Pipeline',
   Pipeline(memory=None,
            steps=[('dtypes',
                    DataTypes_Auto_infer(categorical_features=['teamConf',
                                                               'opptConf',
                                                               'teamAbbr',
                                                               'opptAbbr',
                                                               'teamDiv',
                                                               'opptDiv'],
                                         display_types=True, features_todrop=[],
                                         id_columns=[],
                                         ml_usecase='classification',
                                         numerical_features=['Unnamed: 0',
                                                             'teamDayOff',
                                                             'opptDayOff',
                                                             'oppt2P%_cum_mean',
                                                             'opptAway2P%_cum_mean',
                                                             'oppt2PA_cum_mean',
                                                             'oppt...
                   ('dummy', Dummify(target='teamRslt')),
                   ('fix_perfect', Remove_100(target='teamRslt')),
                   ('clean_names', Clean_Colum_Names()),
                   ('feature_select',
                    Advanced_Feature_Selection_Classic(ml_usecase='classification',
                                                       random_state=123,
                                                       subclass='binary',
                                                       target='teamRslt',
                                                       top_features_to_pick=0.19999999999999996)),
                   ('fix_multi', 'passthrough'), ('dfs', 'passthrough'),
                   ('pca', 'passthrough')],
            verbose=False))],
 False,
 -1,
 <MLUsecase.CLASSIFICATION: 1>,
 -1,
 {'USI',
  'X',
  'X_test',
  'X_train',
  '_all_metrics',
  '_all_models',
  '_all_models_internal',
  '_available_plots',
  '_gpu_n_jobs_param',
  '_internal_pipeline',
  '_ml_usecase',
  'create_model_container',
  'data_before_preprocess',
  'display_container',
  'exp_name_log',
  'experiment__',
  'fix_imbalance_method_param',
  'fix_imbalance_param',
  'fold_generator',
  'fold_groups_param',
  'fold_param',
  'fold_shuffle_param',
  'gpu_param',
  'html_param',
  'imputation_classifier',
  'imputation_regressor',
  'iterative_imputation_iters_param',
  'log_plots_param',
  'logging_param',
  'master_model_container',
  'n_jobs_param',
  'prep_pipe',
  'pycaret_globals',
  'seed',
  'stratify_param',
  'target_param',
  'transform_target_method_param',
  'transform_target_param',
  'y',
  'y_test',
  'y_train'},
 10,
 {'lr': <pycaret.containers.models.classification.LogisticRegressionClassifierContainer at 0x293f6d097c0>,
  'knn': <pycaret.containers.models.classification.KNeighborsClassifierContainer at 0x293f6d09e80>,

In [10]:
best_model = compare_models()

In [36]:
lr = create_model('lr')
tuned_lr = tune_model(lr)

In [37]:
gbc = create_model('gbc')
tuned_gbc = tune_model(gbc)

Note that this is the same setup grid that was shown in __[Binary Classification Tutorial (CLF101) - Level Beginner](https://github.com/pycaret/pycaret/blob/master/tutorials/Binary%20Classification%20Tutorial%20Level%20Beginner%20-%20%20CLF101.ipynb)__. The only difference here is the customization parameters that were passed to `setup()` are now set to `True`. Also notice that the `session_id` is the same as the one used in the beginner tutorial, which means that the effect of randomization is completely isolated. Any improvements we see in this experiment are solely due to the pre-processing steps taken in `setup()` or any other modeling techniques used in later sections of this tutorial.

Another difference you may have noticed is the `log_experiment` and `experiment_name` parameter we have used within `setup`. This is to log all the modeling activity in this experiment. You will see at the end of this notebook on how you can benefit from this functionality.

In [38]:
et = create_model('et')
tuned_et = tune_model(et)

In [39]:
lightgbm = create_model('lightgbm')
tuned_lightgbm = tune_model(lightgbm)

In [40]:
ridge = create_model('ridge')
tuned_ridge = tune_model(ridge)

In [41]:
lda = create_model('lda')
tuned_lda = tune_model(lda)

In [42]:
rf = create_model('rf')
tuned_rf = tune_model(rf)

In [43]:
ada = create_model('ada')
tuned_ada = tune_model(ada)

In [44]:
nb = create_model('nb')
tuned_nb = tune_model(nb)

In [46]:
svm = create_model('svm')
tuned_svm = tune_model(svm)

In [47]:
knn = create_model('knn')
tuned_knn = tune_model(knn)

In [48]:
dt = create_model('dt')
tuned_dt = tune_model(dt)

In [49]:
qda = create_model('qda')
tuned_qda = tune_model(qda)

# Feature Selection and Normalization

In [12]:
exp_clf2 = setup(data = data, target = 'teamRslt', session_id=123,
                  normalize = True, 
                  transformation = False, 
                  ignore_low_variance = False,
                  remove_multicollinearity = False, multicollinearity_threshold = 0.95,
                  numeric_features = num_col_list,
                  categorical_features = ['teamConf', 'opptConf', 'teamAbbr', 'opptAbbr',  'teamDiv' , 'opptDiv'],
#                   ordinal_features = ordinal_dict,
                   data_split_stratify = False,
                   pca = False,
                   feature_selection = True,
                   fix_imbalance = False)
                   #group_features = group_list)
#                   log_experiment = True, experiment_name = 'test1')

In [51]:
best_model = compare_models()

# Feature Selection, Normalization, Transformation

In [52]:
exp_clf3 = setup(data = data, target = 'teamRslt', session_id=123,
                  normalize = True, 
                  transformation = True, 
                  ignore_low_variance = False,
                  remove_multicollinearity = False, multicollinearity_threshold = 0.95,
                  numeric_features = num_col_list,
                  categorical_features = ['teamConf', 'opptConf', 'teamAbbr', 'opptAbbr',  'teamDiv' , 'opptDiv'],
#                   ordinal_features = ordinal_dict,
                   data_split_stratify = False,
                   pca = False,
                   feature_selection = True,
                   fix_imbalance = False)
                   #group_features = group_list)
#                   log_experiment = True, experiment_name = 'test1')

In [53]:
best_model = compare_models()

# Feature Selection, Normalization, Ignore Low Variance

In [54]:
exp_clf4 = setup(data = data, target = 'teamRslt', session_id=123,
                  normalize = True, 
                  transformation = False, 
                  ignore_low_variance = True,
                  remove_multicollinearity = False, multicollinearity_threshold = 0.95,
                  numeric_features = num_col_list,
                  categorical_features = ['teamConf', 'opptConf', 'teamAbbr', 'opptAbbr',  'teamDiv' , 'opptDiv'],
#                   ordinal_features = ordinal_dict,
                   data_split_stratify = False,
                   pca = False,
                   feature_selection = True,
                   fix_imbalance = False)
                   #group_features = group_list)
#                   log_experiment = True, experiment_name = 'test1')

In [55]:
best_model = compare_models()

# Feature Selection, Normalization, Remove_multicolinearity

In [56]:
exp_clf5 = setup(data = data, target = 'teamRslt', session_id=123,
                  normalize = True, 
                  transformation = False, 
                  ignore_low_variance = False,
                  remove_multicollinearity = True, multicollinearity_threshold = 0.95,
                  numeric_features = num_col_list,
                  categorical_features = ['teamConf', 'opptConf', 'teamAbbr', 'opptAbbr',  'teamDiv' , 'opptDiv'],
#                   ordinal_features = ordinal_dict,
                   data_split_stratify = False,
                   pca = False,
                   feature_selection = True,
                   fix_imbalance = False)
                   #group_features = group_list)
#                   log_experiment = True, experiment_name = 'test1')

In [57]:
best_model = compare_models()

# Feature Selection, Normalization, Remove_multicolinearity, data_split_stratify

In [58]:
exp_clf6 = setup(data = data, target = 'teamRslt', session_id=123,
                  normalize = True, 
                  transformation = False, 
                  ignore_low_variance = False,
                  remove_multicollinearity = True, multicollinearity_threshold = 0.95,
                  numeric_features = num_col_list,
                  categorical_features = ['teamConf', 'opptConf', 'teamAbbr', 'opptAbbr',  'teamDiv' , 'opptDiv'],
#                   ordinal_features = ordinal_dict,
                   data_split_stratify = True,
                   pca = False,
                   feature_selection = True,
                   fix_imbalance = False)
                   #group_features = group_list)
#                   log_experiment = True, experiment_name = 'test1')

In [59]:
best_model = compare_models()

# Feature Selection, Normalization, Remove_multicolinearity, data_split_stratify, PCA

In [60]:
exp_clf7 = setup(data = data, target = 'teamRslt', session_id=123,
                  normalize = True, 
                  transformation = False, 
                  ignore_low_variance = False,
                  remove_multicollinearity = True, multicollinearity_threshold = 0.95,
                  numeric_features = num_col_list,
                  categorical_features = ['teamConf', 'opptConf', 'teamAbbr', 'opptAbbr',  'teamDiv' , 'opptDiv'],
#                   ordinal_features = ordinal_dict,
                   data_split_stratify = True,
                   pca = True,
                   feature_selection = True,
                   fix_imbalance = False)
                   #group_features = group_list)
#                   log_experiment = True, experiment_name = 'test1')

In [61]:
best_model = compare_models()

# Feature Selection, Normalization, Remove_multicolinearity, data_split_stratify, PCA, ordinal

In [62]:
data['gmDate'] = data['gmDate'].astype('string')
list_season=data["seasonID"].unique()
list_season = sorted(list_season)
list_date =data["gmDate"].unique()
list_date = sorted(list_date)
ordinal_dict = {"seasonID" : list_season, "gmDate" : list_date}
# col_list = dataframe.columns.to_list()
# group_list1 = [ ["team"+x[4:],"oppt"+x[4:]] for x in num_col_list if x[:4] == "team" and x[4:8]!="Home"]
# group_list2 = [ ["team"+"Home"+x[8:],"oppt"+"Away"+x[8:]] for x in num_col_list if x[:4] == "team" and x[4:8]=="Home"]
# group_list = group_list1 + group_list2

In [63]:
exp_clf8 = setup(data = data, target = 'teamRslt', session_id=123,
                  normalize = True, 
                  transformation = False, 
                  ignore_low_variance = False,
                  remove_multicollinearity = True, multicollinearity_threshold = 0.95,
                  numeric_features = num_col_list,
                  categorical_features = ['teamConf', 'opptConf', 'teamAbbr', 'opptAbbr',  'teamDiv' , 'opptDiv'],
                  ordinal_features = ordinal_dict,
                   data_split_stratify = True,
                   pca = True,
                   feature_selection = True,
                   fix_imbalance = False)
                   #group_features = group_list)
#                   log_experiment = True, experiment_name = 'test1')

In [65]:
best_model = compare_models()

# best so far on Default Models # Feature Selection, Normalization, Remove_multicolinearity, data_split_stratify

# second so far on Default Models # Feature Selection, Normalization, Remove_multicolinearity, data_split_stratify, PCA

# Optimization is time consuming so we prefer PCA with many reduced features to optimize

In [103]:
# from pycaret.datasets import get_data
# dataset = get_data('credit', profile=True)
import pandas as pd

dataset = pd.read_excel('C:/Users/Stavros/Desktop/0. Dummy/0_Dummy.xlsx')

In [104]:
data = dataset.sample(frac=0.95, random_state=786)
data_unseen = dataset.drop(data.index)

data.reset_index(inplace=True, drop=True)
data_unseen.reset_index(inplace=True, drop=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions ' + str(data_unseen.shape))

Data for Modeling: (7010, 209)
Unseen Data For Predictions (369, 209)

In [105]:
num_col_list = list(data.columns)
num_col_list.remove('teamRslt')
num_col_list.remove('teamConf')
num_col_list.remove('opptConf')
num_col_list.remove('teamAbbr')
num_col_list.remove('opptAbbr')
num_col_list.remove('teamDiv')
num_col_list.remove('opptDiv')
num_col_list.remove('seasonID')
num_col_list.remove('gmDate')

In [73]:
exp_clf7 = setup(data = data, target = 'teamRslt', session_id=123,
                  normalize = True, 
                  transformation = False, 
                  ignore_low_variance = False,
                  remove_multicollinearity = True, multicollinearity_threshold = 0.95,
                  numeric_features = num_col_list,
                  categorical_features = ['teamConf', 'opptConf', 'teamAbbr', 'opptAbbr',  'teamDiv' , 'opptDiv'],
#                   ordinal_features = ordinal_dict,
                   data_split_stratify = True,
                   pca = True,
                   feature_selection = True,
                   fix_imbalance = False)
                   #group_features = group_list)
#                   log_experiment = True, experiment_name = 'test1')

In [74]:
best_model = compare_models()

In [75]:
lr = create_model('lr')
tuned_lr = tune_model(lr)

In [76]:
gbc = create_model('gbc')
tuned_gbc = tune_model(gbc)

In [77]:
et = create_model('et')
tuned_et = tune_model(et)

In [78]:
lightgbm = create_model('lightgbm')
tuned_lightgbm = tune_model(lightgbm)

In [79]:
ridge = create_model('ridge')
tuned_ridge = tune_model(ridge)

In [80]:
lda = create_model('lda')
tuned_lda = tune_model(lda)

In [81]:
rf = create_model('rf')
tuned_rf = tune_model(rf)

In [82]:
ada = create_model('ada')
tuned_ada = tune_model(ada)

In [83]:
nb = create_model('nb')
tuned_nb = tune_model(nb)

In [84]:
svm = create_model('svm')
tuned_svm = tune_model(svm)

In [85]:
knn = create_model('knn')
tuned_knn = tune_model(knn)

In [86]:
dt = create_model('dt')
tuned_dt = tune_model(dt)

In [87]:
qda = create_model('qda')
tuned_qda = tune_model(qda)

# all before + min-max scaler

In [10]:
exp_clf10 = setup(data = data, target = 'teamRslt', session_id=123,
                  normalize = True,
                  normalize_method = 'minmax',
                  transformation = False, 
                  ignore_low_variance = False,
                  remove_multicollinearity = True, multicollinearity_threshold = 0.95,
                  numeric_features = num_col_list,
                  categorical_features = ['teamConf', 'opptConf', 'teamAbbr', 'opptAbbr',  'teamDiv' , 'opptDiv'],
#                   ordinal_features = ordinal_dict,
                   data_split_stratify = True,
                   pca = True,
                   feature_selection = True,
                   fix_imbalance = False)
                   #group_features = group_list)
#                   log_experiment = True, experiment_name = 'test1')

In [11]:
best_model = compare_models()

In [90]:
lr = create_model('lr')
tuned_lr = tune_model(lr)

In [91]:
gbc = create_model('gbc')
tuned_gbc = tune_model(gbc)

In [92]:
et = create_model('et')
tuned_et = tune_model(et)

In [93]:
lightgbm = create_model('lightgbm')
tuned_lightgbm = tune_model(lightgbm)

In [94]:
ridge = create_model('ridge')
tuned_ridge = tune_model(ridge)

In [95]:
lda = create_model('lda')
tuned_lda = tune_model(lda)

In [96]:
rf = create_model('rf')
tuned_rf = tune_model(rf)

In [97]:
ada = create_model('ada')
tuned_ada = tune_model(ada)

In [98]:
nb = create_model('nb')
tuned_nb = tune_model(nb)

In [99]:
svm = create_model('svm')
tuned_svm = tune_model(svm)

In [100]:
knn = create_model('knn')
tuned_knn = tune_model(knn)

In [101]:
dt = create_model('dt')
tuned_dt = tune_model(dt)

In [102]:
qda = create_model('qda')
tuned_qda = tune_model(qda)